FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY main.js /usr/share/nginx/html/main.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY default.conf /etc/nginx/conf.d/default.conf

